from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain_classic.agents import AgentExecutor
from langchain_classic.agents.react.agent import create_react_agent
from langchain_classic import hub
from langchain_core.prompts import PromptTemplate
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langchain_ollama import ChatOllama
from langchain_tavily import TavilySearch
from pydantic import BaseModel, Field

load_dotenv()

# Models

class Source(BaseModel):
    """Schema for a source used by the agent."""

    url: str = Field(description="The URL of the source")


class AgentResponse(BaseModel):
    """Schema for the agent response."""

    answer: str = Field(description="The final answer generated by the agent")
    sources: list[Source] = Field(
        description="List of sources used by the agent to generate the answer"
    )


information = """
LangChain is a framework for developing applications powered by language models. 
It can be used for chatbots, Generative Question-Answering (GQA), summarization, and much more.
"""

# summary_template = "Summarize the following text:\n\n{information}\n\nSummary:"

# summary_prompt_template = PromptTemplate(
#     input_variables=["information"],
#     template=summary_template
#     )

llm = ChatOpenAI(model="gpt-4", temperature=0)

# llm = ChatOllama(temperature=0, model="gemma3:270m")
react_prompt = hub.pull("hwchase17/react")
tools = [TavilySearch()]
agent = create_react_agent(
    llm=llm,
    tools=tools,
    prompt=react_prompt,
)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
chain = agent_executor
# response = chain.invoke(input={"information": information})
# print(response.content)

# ReAct = Reason + Act

def main():
    print("Running langchain Agent!")
    result = chain.invoke(
        input = {
            "input": "search for 3 job positions for an AI engineer (langchain specifically)"
                " check only for the last week, in colombia or a remote position and summarize the results."
        }
    )
    print(result)


if __name__ == "__main__":
    main()
